name: FTP Deploy

on:
  push:
    branches:
      - main  # change if needed

jobs:
  ftp-deploy:
    if: github.ref == 'refs/heads/main' && github.event.head_commit.message != 'Updating App version'
    name: Build & Upload Angular App to FTP Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # or your Angular Node version

    - name: Install dependencies
      run: npm ci --force

    - name: Build Angular project
      run: 
            npm run build -- --configuration dev
            npm version ${{env.version}} --no-git-tag-version --allow-same-version
            npm version patch -m "[RELEASE] %s" --no-git-tag-version --allow-same-version
            CURRENT_VERSION=$(node -p "require('./package.json').version")
            UPDATED_VERSION=$(node -p "require('./package.json').version")
            git add package.json
            [ -f package-lock.json ] && git add package-lock.json
            git commit -m "Updating App version"
            git push main
    - name: Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 217.21.85.163
        username: u139672595.ShreeCement
        password: T7g/7+Nx6hGUv?(89lJ'
        local-dir: ./dist/s/  # adjust this if your Angular project name is different
